# Generated by Django 3.0.8 on 2020-08-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproject',
            old_name='subproject_n',
            new_name='number_of_scenes',
        ),
    ]
