# Generated by Django 3.0.8 on 2020-08-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200802_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='client_approved_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='client_approved_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='leader_approved_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='leader_approved_text',
            field=models.BooleanField(default=True),
        ),
    ]
