# Generated by Django 3.0.8 on 2020-08-08 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20200808_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Employee',
        ),
    ]
