# Generated by Django 3.0.8 on 2020-08-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200808_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='useri_id',
            new_name='user_id',
        ),
    ]
